wandb_version: 1

batch_size:
  value: 8
learning_rate:
  value: 2.0e-05
lr_scheduler_type:
  value: cosine
model_name:
  value: VectorGraphics/svg-encoder-base
model_revision:
  value: main
num_train_epochs:
  value: 2
task_name:
  value: sgp-bench
weight_decay:
  value: 0
